### ISSUE TITLE
Record Constructors in the "checked" Data have p-Prefixes breaking Compilation

### ISSUE THREAD

**Issue by shartte** [ParchmentMC/Compass#26]
For example `net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer`.

```
public record PiecesContainer(List<StructurePiece> pieces) {
[...]
   public PiecesContainer(List<StructurePiece> pPieces) {
        this.pieces = List.copyOf(pPieces);
    }
}
```

**Comment by sciwhiz12** [comment]
The [generator for the sanitized export](https://github.com/ParchmentMC/Compass/blob/4b6928fee7dc90836df3c98e6bcdf05aa4880106/src/main/java/org/parchmentmc/compass/tasks/GenerateSanitizedExport.java#L53-L59) needs to be fixed to avoid modifying the canonical constructor of a record class.
